"""empty message

Revision ID: dc1a8b119e4
Revises: 288cd3dc5a8
Create Date: 2015-02-25 15:15:30.073442

"""

# revision identifiers, used by Alembic.
revision = 'dc1a8b119e4'
down_revision = '288cd3dc5a8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
